apiVersion: v1
kind: Secret
metadata:
  name: feedback-app-secret
type: Opaque
stringData:
  mongodb-uri: "mongodb+srv://<username>:<password>@<cluster-url>/feedback_app?retryWrites=true&w=majority"
  flask-secret-key: "<generate-with-python-secrets-module>"